### ISSUE TITLE
Character sheets

### ISSUE THREAD

**Issue by jehy** [mieow/vtm-character#1]
Hello, Jane! I accidentially found ypur repository on facebook and thaught that you could be also interested in cool printable interactive online character sheets.

Recently I developed web site for character sheets and added the first character sheet for mortal. It is shared on github https://github.com/jehy/WOD-Mortal-charsheet and everyone can use it in their project - it is pure HTML & Javascript.

If you are interested, here is an example on how it looks on web site: charsheet.su/view/wod_mortal/4/

**Comment by mieow** [comment]
Hi Jehy,

Thanks for emailing.  Your character sheet looks really good and fast.

I'm looking to have mine hosted on wordpress.org but have changes to make so that no copyrighted material is included with the source files.  Did you take into consideration White wolf's copyright?  If so, what did you do?

Regards,

Jane

**Comment by jehy** [comment]
Hello! As far as we are speaking about character sheet - no, I don't think that it is neccessary to take copyright into consideration. After all, character sheet is just a tool for player - like dice - and only holds info like character system, disciplines and etc - which can potentially be copyrighted.

But if we are speaking about LARP - yeah, we have a community in Moscow which uses White Wolves's World of Darkness setting - including vampires, warewolves, changelings and etc. And to play it legally, we purchated legal rights for running LARP on old WOD.

**Comment by mieow** [comment]
How did you go about purchasing the rights?  Not that I think I'd need to do it but I'm curious as to what the process is?

**Comment by jehy** [comment]
I don't know the details either. I can provide you with contacts of our masters but nowadays they are overloaded with work and I don't think that theey will be able to provide answer...

I don't that that it is neccessary for your case. After all, we are playing a large scale game with 200+ players, web sites, subscribtion fees and live events...

**Comment by mieow** [comment]
Ah yes, as soon as you have subscriptions you'll need to talk to White Wolf officially.  I won't bother your masters just for the sake of my curiosity. :)

**Comment by jehy** [comment]
By the way - you are free to use charsheet.su character sheets for your LARP - eiher you can use web site (ask users to provide a link and share character sheets) or just fork repository with character sheet https://github.com/jehy/WOD-Mortal-charsheet and implement your own server side :)

I think that character sheet for vampire will appear in two weeks - it is really easy :)

**Comment by mieow** [comment]
I'll keep this in mind, although my plugin is in use for a few larps with the current character generation and database integration already there so it's not something that would happen any time soon.  Also, I have no clue about Javascript.

However, I'm certainly going to point your site at a few people in case they are interested.
